### ISSUE TITLE
Few typos on the docs - missing prefix "ADT"

### ISSUE THREAD

**Issue by msellar-inst** [mjr4077au/PSAppDeployToolkit.WinGet#1]
the docs sometimes miss "adt" in the command or example

### Expected Behavior

The command should match the doc title

### Steps to Reproduce

https://github.com/mjr4077au/PSAppDeployToolkit.WinGet/blob/master/docs/Find-ADTWinGetPackage.mdx
Example shows: **Find-WinGetPackage** -Id Microsoft.PowerShell

https://github.com/mjr4077au/PSAppDeployToolkit.WinGet/blob/master/docs/Install-ADTWinGetPackage.mdx
Example shows:  **Install-WinGetPackage -Id Microsoft.PowerShell**

https://github.com/mjr4077au/PSAppDeployToolkit.WinGet/blob/master/docs/Uninstall-ADTWinGetPackage.mdx
Example shows:  **Uninstall-WinGetPackage -Id Microsoft.PowerShell**

https://github.com/mjr4077au/PSAppDeployToolkit.WinGet/blob/master/docs/Update-ADTWinGetPackage.mdx
Example shows:  **Update-WinGetPackage -Id Microsoft.PowerShell**

### Context (Environment)

* Operating System and version as reported by `$PSVersionTable.OS`:
* PowerShell versions as reported by `$PSVersionTable.PSEdition`:

**Comment by mjr4077au** [comment]
Thanks for the report! This is fixed in https://github.com/mjr4077au/PSAppDeployToolkit.WinGet/commit/66a2d2b3a15e0bb93f30e8aa9eac051ff66c05c8, and is now in the newly released 1.0.0 final.
